import VictimSearch from '../Components/VictimSearch';
import './MainPageArticle.css';
import img1 from'./images/1.jpg';
import img2 from'./images/2.jpg';
import img3 from'./images/3.jpg';
import img4 from'./images/4.jpg';
import img5 from'./images/5.jpg';
import img6 from'./images/6.jpg';

function MainPageArticle() {
    return (
        <div className="main">
            <div className="arti">
                <h1>Pacyfikacja wsi Rudno <br />30.05.1940 r.</h1>
                <hr />
                <h4>Początki prześladowania Polak&oacute;w przez okupanta</h4>
                <p>Od pierwszych dni okupacji niemiecki terror wymierzony był przede wszystkim w przedstawicieli polskich elit politycznych, społecznych i intelektualnych. Zgodnie z rasistowskim stereotypem Polaka panującym w III Rzeszy nazistowscy przyw&oacute;dcy wierzyli, że świadomość narodową posiada tylko polska inteligencja, natomiast lud zajmuje się wyłącznie troską o codzienny byt i jest mu obojętny los państwa. Z tego powodu zakładano, że eksterminacja polskich elit pozwoli zniszczyć polską tożsamość narodową i przekształcić polskie społeczeństwo w bierną masę, służącą w najlepszym razie jako niewykwalifikowana siła robocza dla III Rzeszy. Do grona inteligencji Niemcy nie zaliczali jednak wyłącznie os&oacute;b należących z powodu wykształcenia do określonej warstwy społecznej, lecz wszystkich tych, wok&oacute;ł kt&oacute;rych z racji ich aktywności i postawy m&oacute;gł się rozwijać ruch oporu - a więc ludzi, kt&oacute;rych cechowała aktywność i umiejętności kierownicze. Planowano także likwidację os&oacute;b cieszących się autorytetem w polskim społeczeństwie. Dla tej grupy używano określenia "polska warstwa przyw&oacute;dcza". Zaliczono do niej przede wszystkim: duchownych katolickich, nauczycieli, lekarzy, weterynarzy, oficer&oacute;w w stanie spoczynku, urzędnik&oacute;w, kupc&oacute;w, posiadaczy ziemskich, prawnik&oacute;w, pisarzy, dziennikarzy, pracownik&oacute;w służb mundurowych, jak r&oacute;wnież członk&oacute;w organizacji i stowarzyszeń krzewiących polskość - przede wszystkim Polskiego Związku Zachodniego, Ligi Morskiej i Kolonialnej, Kurkowego Bractwa Strzeleckiego, Towarzystwa Powstańc&oacute;w i Wojak&oacute;w, Związku Strzeleckiego "Strzelec" oraz Towarzystwa Gimnastycznego "Sok&oacute;ł".</p>
                <p>Prześladowania zaczęły się od tzw. akcji "Inteligencja" (Inteligenzaktion), prowadzonej na okupowanych ziemiach polskich między wrześniem 1939 a wiosną 1940 roku, kiedy to Niemcy zamordowali co najmniej 100 000 obywateli polskich. Największe rozmiary akcja eksterminacyjna przybrała na ziemiach wcielonych do Rzeszy. P&oacute;źniej uruchomiono nową akcję pod nazwą A-B (AuBerordentiche Befriedungsaktion) "Nadzwyczajna Akcja Pacyfikacyjna". W ramach niej zamordowano co najmniej 6500 Polak&oacute;w - w tym ok. 3500 przedstawicieli polskich elit politycznych i intelektualnych. Najbardziej znaną zbrodnią popełnioną przez Niemc&oacute;w były masowe egzekucje w Palmirach.</p>
                <p>Na wschodzie Rosjanie w tym czasie dokonywali egzekucji na Polskich żołnierzach w Katyniu, Miednoje i innych miejscach.</p>
                <img className="artIMG" alt="Obraz1" src={img4}></img>
                <h4>Pacyfikacja na mieszkańcach wsi Rudno</h4>
                <p>Niniejsze opracowanie o przebiegu pacyfikacji wsi Rudno dokonanej przez hitlerowc&oacute;w w dniu 30 maja 1940 roku oparto na podstawie relacji bezpośrednich uczestnik&oacute;w tych tragicznych wydarzeń: Wiktora Pajdosza, Karola Masłowskiego, Mikołaja Marciniuka, Franciszka Toczko i Michała Robaka.</p>
                <p>Chodź powszechnie uważa się, że zbrodnia hitlerowska dokonana w Rudnie była dziełem przypadku, zbiegu okoliczności, kt&oacute;re zdecydowały o tym, że właśnie w Rudnie, a nie innej wsi dokonano tego straszliwego mordu na bezbronnych i niewinnych. Wydaje się, że wyb&oacute;r wsi Rudno jako terenu pacyfikacji nie był jednak przypadkowy. Wieś ta wyr&oacute;żniała się spośr&oacute;d okolicznych wiosek nie tylko wielkością i położeniem przy ważnych traktach łączących najbliższe miasta, ale także dużym stopniem uświadomienia narodowego mieszkańc&oacute;w, głębokim przywiązaniem do ojczyzny i religii. Zaznaczyło się to wyraźnie znacznie wcześniej, podczas prześladowań religijnych unit&oacute;w przez władze carskie, gdy Rudno było jednym z centralnych punkt&oacute;w oporu na Podlasiu, dając godny przykład całej okolicy. Ujawniło się to też p&oacute;źniej, gdy mimo krwawej ofiary, złożonej w owym tragicznym dniu 30 maja 1940 roku, wielu mieszkańc&oacute;w Rudna brało udział w organizacjach podziemnych, zbrojnie walcząc z wrogiem. Niemcy już wcześniej podejrzewali, że w Rudnie ukryta jest pewna ilość broni. Nie bez znaczenia jest z pewnością fakt, że na kilkanaście dni przed dniem zbrodni, zorganizowali oni we wsi zebranie jego mieszkańc&oacute;w, w czasie kt&oacute;rego wystąpił m.in. znany powszechnie kat ludności tej części Podlasia - Dykow. Na tym zebraniu Niemcy zażądali wydania ukrytej broni grożąc w przeciwnym wypadku surowymi karami (szczeg&oacute;lnie dotyczyło to członk&oacute;w przedwojennej paramilitarnej organizacji "Sok&oacute;ł" działającej w Rudnie i kt&oacute;rej członkowie posiadali broń). Nikt broni nie oddał. Utwierdziło to Niemc&oacute;w w przekonaniu, że Rudno jest "gniazdem niebezpiecznych bandyt&oacute;w". Z relacji uczestnik&oacute;w zebrania wynika, że już w&oacute;wczas z ust Niemc&oacute;w, a zwłaszcza Dykowa, padły słowa wyraźnej pogr&oacute;żki pod adresem mieszkańc&oacute;w Rudna zapowiadające bestialski mord dokonany dwa tygodnie p&oacute;źniej.</p>
                <p>Bezpośrednim pretekstem dokonania zbrodni stało się zabicie Niemca w nieznanych bliżej okolicznościach 28 maja 1940 roku w lesie G&oacute;rki na torach linii kolejowej Łuk&oacute;w - Lublin, pomiędzy Parczewem, a Milanowem. Na miejsce wypadku przybyła niemiecka ekspedycja karna z Lublina i oddział Selbschutzu złożony z kolonist&oacute;w niemieckich zamieszkujących wsie Cichost&oacute;w i Okalew. Bez żadnego dochodzenia i badań otoczyli pobliską wieś Milan&oacute;w, zamierzając w odwet za śmierć Niemca wymordować 50 jej mieszkańc&oacute;w. Ale w&oacute;jtowi Milanowa, kt&oacute;ry był Niemcem nazwiskiem Schulz, udało się zażegnać niebezpieczeństwo grożące wsi. Schulz przekonał w końcu dowodzącego ekspedycją karną oficera, że w jego wsi nie ma "bandyt&oacute;w" i najprawdopodobniej zasugerował, że owi "bandyci" znajdują się we wsi Rudno.</p>
                <p>Dnia 30 mają 1940 roku o godzinie 900 Niemcy przystąpili do zbrojnej pacyfikacji wsi Rudno. Liczba Niemc&oacute;w, kt&oacute;rzy wkroczyli do wsi na dw&oacute;ch samochodach wynosiła około 90 uzbrojonych. W większości byli to volksdeutsche, niemieccy osadnicy z pobliskich wsi Cichost&oacute;w i Okalew. Wśr&oacute;d nich było dw&oacute;ch oficer&oacute;w z trupimi czaszkami na czapkach (Gestapo), z kt&oacute;rych jeden dowodził całą ekspedycją. Niemcy wjechali do wsi od strony Parczewa - jeden samoch&oacute;d ruszył od razu na drugi koniec wsi, by otoczyć ją z dw&oacute;ch stron. Niezwłocznie też rozpoczęli obławę od strony Parczewa i od strony Komar&oacute;wki, chwytając wszystkich mężczyzn bez względu na wiek. Część Niemc&oacute;w szła przez wieś prowadząc łapankę w poszczeg&oacute;lnych domach i pędząc schwytanych w kierunku zajmującego centralne miejsce we wsi kościoła. Pozostała część Niemc&oacute;w, idących tyralierą przez pola, miała za zadanie zapobiec ucieczkom na pola i w stronę lasu.</p>
                <p>Większość mieszkańc&oacute;w została zupełnie zaskoczona nagłym najściem Niemc&oacute;w i nie podejmowała w og&oacute;le pr&oacute;b ucieczki, łatwo wpadając w ręce niemieckich oprawc&oacute;w. Niekt&oacute;rzy jednak, szczeg&oacute;lnie młodsi, zdając sobie sprawę, że grozi im co najmniej wywiezienie na roboty do Niemiec, pr&oacute;bowali uciekać w stronę lasu. Niemcy strzelali do uciekających. Wtedy właśnie padła pierwsza ofiara - uciekającego przez pola jednego z mieszkańc&oacute;w Rudna, Robaka J&oacute;zefa dosięgły śmiertelne kule ...</p>
                <p>Sam spos&oacute;b chwytania ludzi świadczy o wyjątkowo brutalnej i cynicznej postawie hitlerowskich zbir&oacute;w, kt&oacute;rzy od początku nie ukrywali, że zamierzają rozprawić się krwawo z mieszkańcami Rudna, z "bandytami" jak ich nazywali. Jak wynika z relacji jednego z uczestnik&oacute;w tych zdarzeń, Karola Masłowskiego, Niemcy zastali go pracującego w stodole. Gdy usiłował tłumaczyć się - sądząc, że go chcą wywieść na roboty - że jest jedynym mężczyzną w gospodarstwie, został uderzony przez jednego z Niemc&oacute;w kolbą karabinu. Niemcy zabrali z jego gospodarstwa pieniądze i rower, a na jego protesty i błagania jeden z nich oświadczył cynicznie:</p>
                <p>- Już ty na tym rowerze jeździł nie będziesz!</p>
                <p>Dw&oacute;ch młodych Pan&oacute;w Rybińskich Jan (ur. 1917 - lat 23) i Władysław (ur. 1912 - lat 28) tuż przed łapanką przyszli z pociągu z Milanowa i mieli zamiar zjeść śniadanie. Rodzina prosiła ich o to, aby uciekali albo się schowali. Oni jednak myśleli, że znajomość języka niemieckiego pomoże im się wybronić. Niemcy po tym, jak dowiedzieli się, że niedawno przyszli z pociągu, nie zostawili ich i zabrali z innymi, uznając ich za podejrzanych.</p>
                <p>Podobnie postępowali z innymi mieszkańcami Rudna. Wszelkie pr&oacute;by oporu, gry na zwłokę, były likwidowane kolbami karabin&oacute;w. Hitlerowcy wcale nie zważali na wiek schwytanych mężczyzn: pędzono zar&oacute;wno szesnastoletnich chłopc&oacute;w, jak i siedemdziesięcioletnich starc&oacute;w. Wszystkich pędzono pod kości&oacute;ł, gdzie oficer niemiecki, dowodzący akcją wyznaczył punkt zborny. W kr&oacute;tkim czasie spędzono przed kości&oacute;ł parafialny około 170 mężczyzn. Kazano im usiąść na ziemi. Niemcy otoczyli ze wszystkich stron całą gromadę z bronią gotową do strzału tak, że ucieczka była zupełnie niemożliwa. Ze znajdującej się naprzeciwko kościoła szkoły przyprowadzili dw&oacute;ch nauczycieli, prowadzących w tym czasie lekcje: kierownika Antoniego Zagańczyka oraz Tomasza Kowaluka. Dołączono ich do schwytanej grupy.</p>
                <p>Oficerowie niemieccy w towarzystwie kilku innych Niemc&oacute;w udali się na plebanię. Ksiądz Roman Ryczkowski, proboszcz parafii Rudno, przebywał w tym czasie na plebanii - po odprawieniu o godz. 800 Mszy św. z procesją jako, że w tym dniu przypadała oktawa Bożego Ciała. Oficer dowodzący akcją polecił odprowadzić księdza do gromady pojmanych. Wcześniej oświadczyli księdzu, że za zabicie jednego Niemca mają tu zabić sto os&oacute;b. Proboszcz bez wahania powiedział (tak przekazała jego bratowa Anna Ryczkowska), że sam za nich p&oacute;jdzie na śmierć. Niemcy nie wyrazili na to zgody. Ksiądz zapytał, za ile os&oacute;b może on p&oacute;jść. Padła odpowiedź, że może być za pięćdziesięciu ludzi.</p>
                <p>Na plebanii Niemcy kazali sobie podać śniadanie, a następnie wypili wino mszalne. Kiedy zwr&oacute;cono się do nich z prośbą, żeby wina mszalnego nie pili, oficer oświadczył: - Już ten bandyta nie będzie pił więcej wina!</p>
                <p>W tym czasie wok&oacute;ł spędzonych mężczyzn zebrał się spory tłum kobiet, kt&oacute;re przyniosły im żywność oraz odzież. Jeszcze w&oacute;wczas panowało powszechne przekonanie, że mężczyźni zostaną wywiezieni do Niemiec. Ale sami Niemcy, kt&oacute;rzy nie pozwalali wręczać odzieży i żywności, oświadczyli z cynizmem: "tym bandytom to zupełnie będzie niepotrzebne", dawali tym do zrozumienia, że nie chodzi tu o zwykłą łapankę na roboty, ale o krwawą rozprawę z ludnością Rudna, mając na celu zastraszenie całej okolicy. Ludziom trudno było w&oacute;wczas w to uwierzyć, nikt zapewne nie przewidywał dalszego rozwoju wydarzeń. ...</p>
                <img className="artIMG" alt="Obraz1" src={img2}></img>
                <p>Po powrocie oficer&oacute;w z plebanii Niemcy kazali wszystkim wstać, odrzucić żywność oraz cięższą odzież, założyć obie ręce na kark. Popędzili ich przez wieś do gościńca Jabłoń - Radzyń, a następnie gościńcem w stronę odległego o ok. 2 km lasu. Cały czas pędzono ludzi biegiem, a gromadę biegnących otaczał szpaler hitlerowskich oprawc&oacute;w z bronią gotową do strzału. Niemcy zwolnili dopiero w&oacute;wczas, gdy potknął się i upadł na ziemię jeden z najstarszych w gromadzie schwytanych - przeszło 70 &ndash; letni staruszek Aleksander Mirończuk (Bożyk). Wtedy dowodzący ekspedycją karną oficer niemiecki polecił zatrzymać tragiczny poch&oacute;d. W tym właśnie miejscu nastąpiła tzw. "wybi&oacute;rka" - spośr&oacute;d prawie dwustuosobowej gromady Niemcy zaczęli wybierać 50 os&oacute;b, kt&oacute;re mieli następnie rozstrzelać w pobliskim lesie. Stwierdzili, że w gromadzie nie ma ani w&oacute;jta ani sołtysa, a ich funkcję z rozkazu Niemc&oacute;w miał spełniać ksiądz Ryczkowski. Zażądano od niego, aby wskazał "podejrzanych", na co ksiądz oświadczył, że takich we wsi nie ma. Zgromadzonych na gościńcu mężczyzn podzielono na trzy grupy. Najpierw oddzielono grupę mężczyzn powyżej 50 lat oraz poniżej 18 lat - tych po "przesłuchaniu", w czasie kt&oacute;rego starszych pytano o syn&oacute;w, gdzie są, co robią itp., w końcu zwolniono i kazano biec, nie oglądając się do wsi, z wyjątkiem tych, kt&oacute;rzy ze względu na spos&oacute;b tłumaczenia wydali się Niemcom "podejrzani" np. Antoni Denisiuk lat 62. Z pozostałych utworzono grupę 50 skazanych na rozstrzelanie oraz grupę zapasową, liczącą ok. 30 os&oacute;b. Trzeba tu podkreślić, m&oacute;wiąc o tej "selekcji" bezbronnych i niewinnych, bohaterską postawę księdza Ryczkowskiego, kt&oacute;ry starał się dopom&oacute;c przesłuchiwanym i potwierdzał wszystkie ich tłumaczenia, mimo iż zdawał sobie sprawę z grożącego niebezpieczeństwa. Z relacji Karola Masłowskiego wynika, że ksiądz był blady, a w czasie pędzenia gromady pod las powiedział: - Panie Masłowski! Koniec z nami!</p>
                <p>Podczas "wybi&oacute;rki" w grupie 50 znalazł się Michał Robak, kt&oacute;ry zaczął się tłumaczyć, że w domu nie ma nikogo, by go m&oacute;gł ktoś w pracach domowych zastąpić. Ojciec nie żyje, brat jest na robotach w Niemczech. "Jeden z nas to może wam już wystarczy..." Niemiec każe mu znowu powt&oacute;rzyć, wtedy pyta się, czy w grupie zwalnianej jest jakiś kawaler? Zgłasza się pan Szymon Kucyk. Gdy powiedział, że w domu zostały siostra i matka, a brat u nich w niewoli w oflagu, został natychmiast zabrany do grupy pięćdziesięciu, a zwolniony Michał Robak. Poszedł on dobrowolnie na śmierć za niego.</p>
                <p>Wśr&oacute;d 50 mężczyzn przeznaczonych na rozstrzelanie, znalazło się kilku Żyd&oacute;w, kilku mieszkańc&oacute;w Warszawy, kt&oacute;rzy zamieszkiwali w Rudnie od początku wojny oraz kilku mieszkańc&oacute;w z sąsiednich wsi, kt&oacute;rzy przypadkowo znaleźli się w Rudnie w czasie łapanki. Ogromną większość, bo ok. 40 os&oacute;b stanowili mieszkańcy Rudna. Charakterystyczny wydaje się fakt, że w tej grupie znaleźli się ludzie posiadający wykształcenie: obaj nauczyciele Antoni Zagańczyk i Tomasz Kowaluk, student Michał Bobruk, a także dołączony p&oacute;źniej ksiądz Roman Ryczkowski. Przeważali w niej zdecydowanie ludzie młodzi, kt&oacute;rzy Niemcom wydawali się najbardziej "podejrzani", jako ukrywający się lub też potencjalni "bandyci", kt&oacute;rych trzeba wytępić.</p>
                <p>Po wybraniu grupy skazanych os&oacute;b, oficer niemiecki pojechał samochodem sprawdzić szykowany na miejscu egzekucji d&oacute;ł w lesie, w kt&oacute;rym miano zasypać ciała pomordowanych. Na miejsce zbrodni Niemcy wybrali leśną polanę w pobliżu majątku Planta. Szpadlami i łopatami zabranymi z Rudna pogłębili d&oacute;ł, z kt&oacute;rego mieszkańcy okolicznych wiosek wydobywali żwir i piasek dla cel&oacute;w budowlanych. Ten d&oacute;ł miał być wsp&oacute;lną mogiłą wielu bezbronnych i niewinnych ludzi ....</p>
                <p>Po powrocie z lasu niemiecki oficer zaczął jeszcze raz liczyć ową pięćdziesięcioosobową grupę - dokonał przy tym kilku uzupełnień i zmian. Miedzy innymi zwolnił jednego z tej grupy, Pajdosza Wiktora, kt&oacute;ry na kolanach błagał o zwolnienie, ponieważ miał małe dzieci. Był on ostatnim uwolnionym. Po kilkakrotnym, dokładnym przeliczeniu tej grupy i włączeniu do niej księdza Ryczkowskiego, Niemcy rozkazali pozostałym z grupy zapasowej biec, nie oglądając się, do wsi, a sami powieźli owych 51 skazanych na rozstrzelanie - w dw&oacute;ch kolejnych transportach, w odstępnie kilkudziesięciu minut - na miejsce egzekucji. W czasie "selekcji" Niemcy strzelali do kobiet, kt&oacute;re z daleka usiłowały obserwować rozgrywające się pod lasem wypadki.</p>
                <p>W tym czasie w Rudnie sądzono początkowo, że Niemcy powieźli tych 50-ciu i proboszcza na roboty. Nie było tu słychać strzał&oacute;w z egzekucji. Strzały i krzyki mordowanych bestialsko przez hitlerowskich oprawc&oacute;w słychać było w pobliskiej wsi Planta. Słyszeli je r&oacute;wnież robotnicy leśni, pracujący w&oacute;wczas w lesie, a także ci, kt&oacute;rym udało się zbiec z Rudna do lasu. Ze względu na to, że nikt z owej 51 osobowej grupy nie pozostał żywy, do dnia dzisiejszego krążą w Rudnie r&oacute;żne wersje wypadk&oacute;w, kt&oacute;re rozegrały się na leśnej polanie już podczas samej egzekucji.</p>
                <img className="artIMG" alt="Obraz1" src={img3}></img>
                <p>Według relacji jednego z mieszkańc&oacute;w Planty, przekazanej Karolowi Masłowskiemu, kt&oacute;ry w czasie egzekucji znalazł się przypadkowo w pobliżu i leżąc w rowie z odległości kilkudziesięciu metr&oacute;w obserwował egzekucję mieszkańc&oacute;w Rudna. Jego opowieść wydaje się najbardziej autentyczna i wiarygodna. Nie znamy jednak jego nazwiska. Ostatni akt tej ponurej tragedii miał następujący przebieg.</p>
                <p><strong>Ot&oacute;ż Niemcy po przywiezieniu pierwszego transportu na leśną polanę wyładowali skazanych, kazali im zejść do dołu i położyć się rzędem, a następnie rozstrzelali ich z karabinu maszynowego. Tych, kt&oacute;rzy nie padli trupem od razu, hitlerowcy oprawcy dobijali strzałami w tył głowy - potwierdziła to p&oacute;źniejsza ekshumacja zwłok, podczas kt&oacute;rej znaleziono w tym miejscu u niekt&oacute;rych ślady po kulach. Pierwszą partię rozstrzelanych przysypano ziemią i wkr&oacute;tce przyjechał samoch&oacute;d z pozostałymi, wśr&oacute;d kt&oacute;rych znalazł się ksiądz Ryczkowski. Obserwujący ten okrutny mord bezbronnych zapamiętał głośny okrzyk (najprawdopodobniej księdza Ryczkowskiego): - To będzie nasza mogiła! O Matuchno Najświętsza! Niemcy rozstrzelali ich podobnie jak pierwszy transport i zasypali ziemią we wsp&oacute;lnym grobie. Po dokonaniu zbrodni - odjechali.</strong></p>
                <p>Według innych relacji ludności Rudna, a w szczeg&oacute;lności prof. Jana Sienkiewicza, ostatni akt tej zbrodni przebiegał tak:</p>
                <p><em>Po przywiezieniu pierwszej grupy więźni&oacute;w, kazano im wysiąść z samochodu i uklęknąć nad dołem. W tej grupie był przywieziony ksiądz Ryczkowski. Ksiądz, odprowadzony na bok, udzielał wszystkim rozstrzeliwanym rozgrzeszenia in articulo mortis i patrzy, jak jego parafianie padają martwi do wykopanego dołu - mogiły. Nie oszczędzono mu niczego, musiał to przeżyć jeszcze dwa razy, a kiedy ostatnim mordowanym oddał ostatnią posługę kapłańską, miał być wolny. Trzykrotnie odprowadzany na drogę prowadzącą do wsi, dokąd kazano mu wr&oacute;cić i przestrzec, że tak będzie karany każdy występek przeciwko Rzeszy Niemieckiej. Za każdym razem wracał, klękał nad tym okrutnym miejscem kaźni i głośno się modlił. Kiedy i za trzecim razem wr&oacute;cił i ukląkł, padł pojedynczy strzał, kt&oacute;ry przerwał i jego, już pewnie teraz niechciane życie. Prawdopodobnie nie m&oacute;gł sobie wyobrazić, że po tym, czego był tragicznym świadkiem, byłby w stanie wr&oacute;cić do świata żywych. Został z nimi. I tu najdobitniej wypełniły się słowa "Dobrym Pasterzu". Ks. Roman Ryczkowski, &oacute;wczesny proboszcz parafii Rudno, niespełna 40-letni, bohaterski kapłan, podzielił los swoich wiernych. Mogiłę przysypano ziemią i jeżdżono po niej samochodami w celu zatarcia ślad&oacute;w zbrodni.</em></p>
                <p>Już tego samego dnia wieczorem ludność Rudna dowiedziała się o tragicznym losie swoich najbliższych, co wywołało powszechną rozpacz. Relacjonujący te wydarzenia Franciszek Toczko stwierdził, że gdy następnego dnia udał się na miejsce rozstrzelania, zobaczył tam ślady krwi i m&oacute;zgu ludzkiego.</p>
                <p>Do końca wojny Niemcy nie pozwolili na przeniesienie ciał pomordowanych na cmentarz parafialny. Ekshumacji dokonano dopiero 22 kwietnia 1945 roku. Ciała leżały w dw&oacute;ch warstwach przysypanych ziemią. Ciała po uroczystej mszy 23 kwietnia 1945 roku przewieziono na cmentarz parafialny i pochowano we wsp&oacute;lnym grobie. W miejscu rozstrzelania postawiono drewniany krzyż. Na wsp&oacute;lnym grobie, znajdującym się niedaleko bramy wejściowej na cmentarzu, postawiono duży pomnik.</p>
                <p>Opisana pacyfikacja wsi Rudno była jedną z pierwszych na terenie powiatu radzyńskiego i parczewskiego.</p>

                <VictimSearch />
                
                <img className="artIMG" alt="Obraz1" src={img5}></img>
                <h3>Wspomnienia mieszkańc&oacute;w wsi Rudno, Bezwola i Planta</h3>
                <p><strong> Nazywam się Jan Denisiuk. Dzisiaj mam 81 lat. Urodziłem się i mieszkam w Rudnie.</strong></p>
                <p>W roku 1940 miałem 6 lat. Pamiętam jak 30 maja po mszy na zakończenie oktawy Bożego Ciała do wioski wkroczył oddział niemieckiego wojska i dokonał aresztowania mężczyzn. Całą grupę, w tym mojego dziadka Denisiuka Antoniego, zgromadzono przed kościołem. Wszyscy siedzieli na ziemi z założonymi rękami. Po przyprowadzeniu nauczyciela Zagańczyka i Kowaluka oraz księdza Ryczkowskiego wszystkich poprowadzono biegiem z założonymi rękami za głowę w stronę gościńca i lasu. Ja się bałem dalej iść i tylko wybiegłem na zagumienie. Pamiętam jak z Trzeciego Rudna prowadzono Pana Robaka, to on uciekł w zboże, a inny Niemiec strzelił do niego raniąc go. Mojemu koledze Stanisławowi Abramczukowi zabrano ojca. Gdy wszystkich już wyprowadzono na drogę do lasu, on pobiegł za nimi aż do miejsca selekcji, gdzie bardzo płakał i nie chciał puścić swego ojca. Dzięki temu uratował swego tatę. Zwolnieni z miejsca selekcji m&oacute;wili, że wr&oacute;cił dzięki temu chłopcu, kt&oacute;ry tak mocno płakał za ojcem.</p>
                <p>Rudno 10.02.2015 r.</p>
                <hr />
                <p><strong>Nazywam się Kopeć Władysław, urodziłem się 30.12.1918 roku w Kałudze pod Moskwą.</strong></p>
                <p>Ze zdarzeń 30 maja 1940 (a miałem wtedy 21 lat) pamiętam, jak pracując przy załadunku ziemniak&oacute;w w dworze Planta, nadjechała około południa grupa żołnierzy niemieckich w czarnych mundurach i zażyczyli sobie furmanki do przewozu w lesie. Zostałem wyznaczony do tego i pojechałem do lasu z jednym z żołnierzy. Wcześniej z lasu było słychać strzały. Po dojechaniu na miejsce egzekucji zobaczyłem innego Niemca z karabinem maszynowym, kt&oacute;ry miałem zawieść z nim do miejscowości Derewiczna. W lesie była zasypana mogiła, a spod ziemi wysączała się krew i ziemia się ruszała. Po załadowaniu karabinu odwiozłem Niemca do Derewicznej na skrzyżowanie drogi Komar&oacute;wka &ndash; Parczew. Podczas jazdy bardzo się bałem o swoje życie. P&oacute;źniej w czasie wojny baliśmy się chodzić w miejsce egzekucji.</p>
                <p>Planta 05.04.2010 r.</p>
                <hr />
                <p><strong>Nazywam się Krystyna Bagniuk. Dzisiaj mam 69 lat. Urodziłam się i wychowałam w Bezwoli. Tutaj też chodziłam do szkoły. Wyszłam za mąż za Henryka Bagniuka. Moimi rodzicami byli Marianna i Stanisław Kawałczukowie. </strong></p>
                <p><strong>- Co pani wie o wydarzeniach z 30 maja 1940 roku?</strong></p>
                <p>Zamordowania w lesie Planta parafian z Rudna i ich księdza prawie nie pamiętam. Mieszkaliśmy przecież w Bezwoli. Natomiast w pamięci utrwaliło mi się następujące wydarzenie. Tego dnia nasz tata wyjeżdżał z domu koniem. Kiedy wr&oacute;cił był bardzo przejęty. Powiedział do nas, że tak niewiele brakowało, byście mnie już nie zobaczyli. Od tego czasu żył w ciągłym strachu. Była to dziwna choroba, jakby nerwica. Miał kłopoty z chodzeniem. Powiadał, żeby nie ten Niemiec, to ja bym pożył. Umarł 26 lipca 1943 roku. Został pochowany na cmentarzu w Wohyniu.</p>
                <p><strong>- Może kt&oacute;reś z rodzic&oacute;w opowiadało o tym dramacie w lesie Planta?</strong></p>
                <p>Wiem bardzo mało. Była mowa o tym, że ojciec żył w nieustanym lęku. Przypominam sobie bardzo słabo, że ojciec opowiadał coś o drzewie, ale dzisiaj nie mogę powiedzieć, czy chowając się przed Niemcami wszedł na drzewo, czy pod złożone drewno. <strong>Jest mi znane to, że Stanisław Kawałczuk spotkał tego dnia w lesie znajomego mu folksdojcza pilnującego wykopanego dołu, w kt&oacute;rym miano pochować parafian z Rudna.</strong> Tego nie mogę potwierdzić. Ale tak mogło być. Moi rodzice nie mieli własnego lasu, a opał był potrzebny. Nie wykluczam, że tego dnia m&oacute;gł robić przy drewnie. Jeśli chodzi o spotkanego folksdojcza, to jest bardzo prawdopodobne. Ja jednak o tym nie wiem nic. Nasz tata znał ludzi z Cichostowa. Miał tam swoją przyrodnią siostrę Feliksę. Często u niej bywał. Może stąd ta znajomość. Wiadomo przecież, że niekt&oacute;rzy mężczyźni z Okalewa i Cichostowa brali udział w pacyfikacji, bo to byli koloniści niemieccy.</p>
                <p>Bezwola 20.07.2000 r.</p>
                <hr />
                <p><strong>Nazywam się Kuzko Alicja, mam lat 70. Urodziłam się w Rudnie. Moi rodzice to Tomasz Furman i Maria z Paraci&oacute;w. Tutaj mieszkam całe życie. Do szkoły też tu chodziłam. Wyszłam za mąż za Tomasza Kuzko, kt&oacute;ry pochodzi z tej samej miejscowości. - Jak Pani wspomina wydarzenia z 30 maja 1940 roku? </strong></p>
                <p>Miałam wtedy 10 lat. Ale wszystko dokładnie pamiętam. Był to dzień zakończenia oktawy Bożego Ciała. Z babcią (Natalią Furman) wracałam z kościoła. Spotkałyśmy ludzi pędzonych przez Niemc&oacute;w. Ludzie szli całą drogą. Miałam w ręku wianeczki. W domu nie było dziadka i taty. Wszystkich gromadzono przed kościołem.</p>
                <p><strong>- Co mogło się dziać na plebanii w Rudnie?</strong></p>
                <p>Naszym proboszczem był ksiądz Roman Ryczkowski. Pamiętam go bardzo słabo. Uczył mnie religii i udzielił I Komunii św. To co teraz powiem znam z opowiadania Ryczkowskiej Anny (już nie żyje). Była bratową ks. Ryczkowskiego. Pochodziła z rodziny Karwackich (Anna Ryczkowska była przyrodnią siostrą ojca ks. Karwackiego). Ojca jej nie pamiętam, natomiast mama miała na imię Marta.</p>
                <p><strong>- Proszę przybliżyć te tragiczne chwile.</strong></p>
                <p>Część Niemc&oacute;w pilnowała zgonionych mężczyzn (kobiet tam nie było), natomiast starszyzna udała się na plebanię. Kazali przygotować sobie śniadanie. Oświadczyli księdzu, że za zabicie jednego Niemca mają tu zabić sto os&oacute;b. Proboszcz bez wahania powiedział (tak m&oacute;wiła bratowa Anna Ryczkowska), że sam za nich p&oacute;jdzie na śmierć. Niemcy nie wyrazili na to zgody. Ksiądz zapytał za ile os&oacute;b może on p&oacute;jść. Padła odpowiedź, że może być za pięćdziesięciu ludzi. Na plebanii była rodzina ks. Ryczkowskiego. Był brat z żoną, była też siostra Stefania (już nie żyje). Mieszkała potem w Komar&oacute;wce Podlaskiej. Była też jedna siostra księdza &ndash; Zuzanna. Była to osoba kaleka. Miała zgarbienie kręgosłupa.</p>
                <p><strong>- A co z Pani dziadkiem i ojcem?</strong></p>
                <p>Dziadka Stefana wkr&oacute;tce odesłali do domu. Miał wtedy ponad 70 lat. Natomiast tata Tomasz kilkakrotnie podchodził do Niemca i prosił o zwolnienie. Tłumaczył, że ma wielodzietną rodzinę (było nas siedmioro rodzeństwa). Niemiec nie wyrażał zgody. Dopiero za piątym razem, kiedy ksiądz proboszcz potwierdził, że ojciec m&oacute;wi prawdę, został zwolniony do domu. To wszystko, ta cała &bdquo;przebi&oacute;rka&rdquo; miała miejsce za wsią, może 200 metr&oacute;w od lasu. Selekcja, tak jak opowiadał tata, zaczęła się od tego, że jeden z pędzonych, staruszek (był on z III Rudna, dzisiaj nie pamiętam jak się nazywał) zemdlał. Zatrzymano pędzonych i dokonano selekcji. Tych, kt&oacute;rych zwolniono wysłano do dom&oacute;w z poleceniem, by się nie oglądali za siebie. Jako jeden z ostatnich wr&oacute;cił m&oacute;j ojciec.</p>
                <p><strong>- Czy tata coś jeszcze opowiadał o ks. Romanie Ryczkowskim?</strong></p>
                <p>Ksiądz proboszcz wstawiał się za każdym parafianinem. Z miejsca selekcji odwożono ludzi samochodami do lasu. We wsi opowiadano, że proboszcz wszystkich rozgrzeszał. Udzielał im tego sakramentu w lesie przy wykopanym dole. Sam zginął jako ostatni. &bdquo;Rudnianie przepowiadali to tak: Niemcy chcieli księdza puścić do domu. Nie odszedł został przy swoich, bo m&oacute;wił, że będę tu gdzie są moje owce&rdquo;. To się potwierdza tym, co widziałam w czasie ekshumacji w 1945 roku. Był to kwiecień, ale kt&oacute;ry dzień to nie pamiętam. Ciało księdza proboszcza leżało na wierzchu innych ciał, jakby na samym środku.</p>
                <p><strong>- Czy ci, co uczestniczyli w pacyfikacji to rzeczywiście byli Niemcy ?</strong></p>
                <p>Nie, to byli &bdquo;Okalewscy&rdquo;. Ludzie &ndash; koloniści niemieccy mieszkający we wsi Okalew i Cichost&oacute;w. Mieli na sobie ciemne płaszcze, a na głowach czapki z trupimi głowami. Na zakończenie mego zeznania stwierdzam, że ks. Roman Ryczkowski umarł za 50 os&oacute;b, bo Niemcy mieli zabić 100, a zabili 50 i księdza. Tak więc ksiądz proboszcz, oddając swoje życie, uratował 50 os&oacute;b.</p>
                <p>Rudno 16 lipca 2000 r.</p>
                <hr />
                <p><strong>Niemcy zabili jej brata.Pani Anna z Paraci&oacute;w, emerytowana nauczycielka, pochodziz Rudna. Ukończyła Liceum Pedagogiczne w Siedlcach, ale nie podjęła pracy, ponieważ wybuchła wojna. Wr&oacute;ciła więc do rodzinnej wsi.</strong></p>
                <p><em>Dzieci z Komar&oacute;wki i sąsiednich wiosek nie chodziły do szkoły, ponieważ budynek szkoły Niemcy zajęli na magazyny &ndash; m&oacute;wi pani Anna. W maju 1940 roku, kiedy miały miejsce tragiczne wydarzenia w Rudnie, mieszkała tam razem z rodzicami i rodzeństwem. Zginął w&oacute;wczas jej starszy brat Stanisław, a siostrę Niemcy wywieźli na roboty. Pacyfikację i mord w Rudnie wspomina tak: </em></p>
                <p>Ludzie myśleli, że to może na wyw&oacute;zkę na roboty do Niemiec. M&oacute;j brat powiedział, że p&oacute;jdzie do sklepu trzy domy dalej po papierosy na drogę. Wyszedł boso, w koszuli i spodniach. Zatrzymał się chwilę u wujka, kt&oacute;ry mieszkał obok sklepu. Stamtąd go zabrali. Wszystkich zebrali koło szkoły. Był tam też ksiądz Ryczkowski. Niemiec, kt&oacute;ry wybierał mężczyzn pytał księdza: - Znasz go? Niekt&oacute;rych ksiądz wybronił tłumacząc, że mają za dużo dzieci na utrzymaniu albo, że ktoś jest ciężko chory w rodzinie. Wybranych załadowali na ciężar&oacute;wki. Ludzie byli przekonani, że wiozą ich na roboty. Trochę się jednak dziwili, dlaczego po drodze zabierają z dom&oacute;w szpadle i łopaty. Pierwsza ciężar&oacute;wka pojechała do lasu, reszta zatrzymała się przy leśnicz&oacute;wce. Jak się p&oacute;źniej okazało, ci pierwsi kopali w lesie d&oacute;ł dla siebie i pozostałych. Mieszkańcy wsi nie byli pewni, co się stało. Bali się sprawdzić, co jest w świeżo zakopanym dole.</p>
                <p>Mieli nadzieję, szukali u sędzi&oacute;w jakichś wiadomości. Zapłacili za to dużo pieniędzy. Ale chłopcy, tacy po 16, 17 lat, zaczęli nocą zakradać się do lasu i grzebać po omacku. Raz odcięli kawałek materiału, innym razem trochę włos&oacute;w i tak ludzie zaczęli dowiadywać się prawdy o swoich bliskich. Ale dopiero ekshumacja w 1945 roku pokazała całą prawdę. Wśr&oacute;d tych, kt&oacute;rzy w&oacute;wczas zginęli było 49 lub 50 os&oacute;b. Ustalono nazwiska 41 miejscowych, pozostali to Żydzi i jacyś warszawiacy, kt&oacute;rzy w Rudnie przebywali czasowo &ndash; kończy swoje wspomnienia.</p>
                <p>23 kwietnia 1945 roku ekshumowano ciała zamordowanych i ich prochy pochowano we wsp&oacute;lnej mogile na cmentarzu w Rudnie. Od tej pory w każdą rocznicę w kaplicy cmentarnej jest odprawiana msza w ich intencji.</p>
                <p>W 50 rocznicę, to znaczy 30 maja 1990 roku, w miejscu zbrodni ustawiono pomnik (olbrzymi głaz polny) i dębowy krzyż. Została odprawiona też msza św. z udziałem biskupa siedleckiego Jana Mazura oraz kilkunastu księży.</p>
                <p>Zdecydowaliśmy się na publikację tych wspomnień nieprzypadkowo. Mamy informacje, że miejscowa społeczność zabiega o nagłośnienie tych wydarzeń, by szersze grono os&oacute;b poznało wydarzenia, jakie rozegrały się w małej wiosce, jaką jest Rudno. Mamy nadzieję, że w ten spos&oacute;b przyczynimy się chociaż w małej części do tego procesu .</p>
                <p><strong>Stanisław Iwaszko s. Grzegorza i Anny z/d Wołodko, ur. 07.X.1907 r. w Radczu. </strong></p>
                <p><em>Dnia 30 maja 1940 r. ze wsi Radcze szli do lasu Planta po żerdzie : Stanisław i J&oacute;zef Iwaszko, Seweryn Cięciesz, Czesław Kwasowiec i Piotr Kiełbasa. Idąc do lasu, musieli przejść przez wieś Rudno. Nie posłuchali ostrzeżeń jakiejś kobiety, kt&oacute;ra im powiedziała, że w Milanowie zabito Niemca i mogą łapać ludzi. Idących minęły samochody z Niemcami, więc tym śmielej poszli dalej, ale gdy chcieli ze wsi iść w stronę lasu, wtedy Niemcy zatrzymali ich i dołączyli do ludzi zgonionych na placu naprzeciw kościoła we wsi Rudno. Pognano ich pod las. Przy kościele była kobieta z małym dzieckiem na ręku. Dziecko to bardzo płakało. Jeden z Niemc&oacute;w zapytał czyje to jest dziecko i wtedy z kolumny wypuszczono ojca dziecka. Gdy kolumna była pod lasem, kazano wszystkim usiąść. Kilku Niemc&oacute;w pojechało samochodem do lasu, pozostali zaś rozpoczęli selekcjonować. Niemcy kazali księdzu, kt&oacute;ry musiał z nimi chodzić, potwierdzać czy zapytani m&oacute;wią prawdę, tj. czy mają dzieci, czy są kawalerami itp. Gdy ktoś z rodziny jest w Rzeszy na robotach, tego zwalniali. </em></p>
                <p>Po powrocie Niemc&oacute;w z lasu odebranych od reszty, Niemcy policzyli, a reszcie kazali iść do domu. Z Radcza powr&oacute;cił Stanisław Iwaszko i Piotr Kiełbasa s/ Augustyna.</p>
                <p><br />Podpisał: Iwaszko Stanisław <br />Spisał: M. Jędruszczak Radcze 23. VII. 1974 r.</p>
            </div>
        </div>
    );
}

export default MainPageArticle;