export const spisOfiar = [
    {
        id: 1,
        opis: 'Ryczkowski Roman',
        urodzony: "ur. 1910",
        imgPATH: '',
    },
    {
        id: 2,
        opis: 'Zagańczyk Antoni',
        urodzony: "ur. 1910",
        imgPATH: '',
    },
    {
        id: 3,
        opis: 'Kowaluk Tomasz',
        urodzony: "ur. 1907",
        imgPATH: '',
    },
    {
        id: 4,
        opis: 'Bobruk Michał',
        urodzony: "ur. 1912",
        imgPATH: '',
    },
    {
        id: 5,
        opis: 'Burzec Feliks',
        urodzony: "ur. 1908",
        imgPATH: '',
    },
    {
        id: 6,
        opis: 'Butrym Stanisław',
        urodzony: "ur. 1907",
        imgPATH: '',
    },
    {
        id: 7,
        opis: 'Cięciesz Seweryn',
        urodzony: "ur. 1905",
        imgPATH: '',
    },
    {
        id: 8,
        opis: 'Czuryło Stanisław',
        urodzony: "ur. 1898",
        imgPATH: '',
    },
    {
        id: 9,
        opis: 'Daniłko Ludwik',
        urodzony: "ur. 1908",
        imgPATH: '',
    },
    {
        id: 10,
        opis: 'Deryło Stanisław',
        urodzony: "ur. 1914",
        imgPATH: '',
    },
    {
        id: 11,
        opis: 'Denisiuk Antoni',
        urodzony: "ur. 1878",
        imgPATH: '',
    },
    {
        id: 12,
        opis: 'Furman Józef',
        urodzony: "ur. 1913",
        imgPATH: '',
    },
    {
        id: 13,
        opis: 'Iwaszko Józef',
        urodzony: "ur. 1912",
        imgPATH: '',
    },
    {
        id: 14,
        opis: 'Kiszewski Jerzy',
        urodzony: "ur. 1913",
        imgPATH: '',
    },
    {
        id: 15,
        opis: 'Kucyk Mikołaj',
        urodzony: "ur. 1900",
        imgPATH: '',
    },
    {
        id: 16,
        opis: 'Kucyk Piotr',
        urodzony: "ur. 1917",
        imgPATH: '',
    },
    {
        id: 17,
        opis: 'Kucyk Piotr',
        urodzony: "ur. 1908",
        imgPATH: '',
    },
    {
        id: 18,
        opis: 'Kucyk Szymon',
        urodzony: "ur. 1894",
        imgPATH: '',
    },
    {
        id: 19,
        opis: 'Kuzko Józef',
        urodzony: "ur. 1920",
        imgPATH: '',
    },
    {
        id: 20,
        opis: 'Kuzko Piotr',
        urodzony: "ur. 1905",
        imgPATH: '',
    },
    {
        id: 21,
        opis: 'Kwasowiec Czesław',
        urodzony: "ur. 1919",
        imgPATH: '',
    },
    {
        id: 22,
        opis: 'Łapiuk Władysław',
        urodzony: "ur. 1915",
        imgPATH: '',
    },
    {
        id: 23,
        opis: 'Mazyruk Ludwik',
        urodzony: "ur. 1911",
        imgPATH: '',
    },
    {
        id: 24,
        opis: 'Michalski Józef',
        urodzony: "ur. 1911",
        imgPATH: '',
    },
    {
        id: 25,
        opis: 'Parać Stanisław',
        urodzony: "ur. 1914",
        imgPATH: '',
    },
    {
        id: 26,
        opis: 'Pruszczak Franciszek',
        urodzony: "ur. 1910",
        imgPATH: '',
    },
    {
        id: 27,
        opis: 'Przybylski Leon',
        urodzony: "",
        imgPATH: '',
    },
    {
        id: 28,
        opis: 'Rachubik Feliks',
        urodzony: "ur. 1906",
        imgPATH: '',
    },
    {
        id: 29,
        opis: 'Rachubik Jan',
        urodzony: "ur. 1917",
        imgPATH: '',
    },
    {
        id: 30,
        opis: 'Rachubik Jan',
        urodzony: "ur. 1919",
        imgPATH: '',
    },
    {
        id: 31,
        opis: 'Robak Józef',
        urodzony: "ur. 1895",
        imgPATH: '',
    },
    {
        id: 32,
        opis: 'Rybiński Jan',
        urodzony: "ur. 1917",
        imgPATH: '',
    },
    {
        id: 33,
        opis: 'Rybiński Władysław',
        urodzony: "ur. 1912",
        imgPATH: '',
    },
    {
        id: 34,
        opis: 'Sienkiewicz Jan',
        urodzony: "ur. 1911",
        imgPATH: '',
    },
    {
        id: 35,
        opis: 'Sienkiewicz Stanisław',
        urodzony: "ur. 1919",
        imgPATH: '',
    },
    {
        id: 36,
        opis: 'Szczygieł Franciszek',
        urodzony: "uur. 1914",
        imgPATH: '',
    },
    {
        id: 37,
        opis: 'Szczygieł Ludwik',
        urodzony: "ur. 1919",
        imgPATH: '',
    },
    {
        id: 38,
        opis: 'Szwaj Józef',
        urodzony: "ur. 1914",
        imgPATH: '',
    },
    {
        id: 39,
        opis: 'Waciuta Karol',
        urodzony: "ur. 1905",
        imgPATH: '',
    },
    {
        id: 40,
        opis: 'Watyruk Ludwik',
        urodzony: "ur. 1912",
        imgPATH: '',
    },
    {
        id: 41,
        opis: 'Wołowik Józef',
        urodzony: "ur. 1909",
        imgPATH: '',
    },
    {
        id: 42,
        opis: 'Wołowik Stefan',
        urodzony: "ur. 1900",
        imgPATH: '',
    },
    {
        id: 43,
        opis: 'Wołowik Wincenty',
        urodzony: "ur. 1915",
        imgPATH: '',
    },
    {
        id: 44,
        opis: 'Zając Franciszek',
        urodzony: "ur. 1917",
        imgPATH: '',
    },
];
